### ISSUE TITLE
Page name begining with "Admin" launches Admin instead of the intended page.

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#771] opened 2018-09-08 20:34 UTC
### Describe your problem
I have a Parent Page with a title of "Admin Documentation" and a URL of  "/admin-documentation"
Under it as children, will be Topics.
![bludit admin doc issue](https://user-images.githubusercontent.com/37149377/45258410-d3915a80-b3ae-11e8-9134-ad04c1be865d.png)
### Expected behaviour
When I click it I expect to be taken to that page, i.e. "Admin Documentation"

### Actual behaviour
When I click the "Admin Documentation" link, I am taken to the Admin login, ie "/admin"

### Bludit version 
v3.2.4 & v3-beta-2

**Comment by Elwisz** [comment] 2018-09-09 08:04
This issue is caused by the following comparison: https://github.com/bludit/bludit/blob/f0895796cd270ee39f64487d94996878c7fa4f9a/bl-kernel/url.class.php#L61

**Comment by dignajar** [comment] 2018-09-09 16:16
Nice bug.. checking for fix it

**Comment by dignajar** [comment] 2018-09-10 16:35
@anaggh fix it, but the final URL for the admin is `/admin/`.. I going to check to do a redirect `/admin` to `/admin/`

**Comment by dignajar** [comment] 2018-09-10 20:41
Fixed in Bludit v3.0.0 rc3

**Closed by dignajar** 2018-09-10 20:41 UTC
