### ISSUE TITLE
[Idea] Quick link settings

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#910] opened 2019-01-12 10:01 UTC
### Describe your problem
For example, I'd prefer 'Existing Content' as a quick link instead of Forum.

### Expected behavior
Go to settings area and select/deselect the items I want.

Maybe have a maximum. Is 8 possible?

### Actual behavior
Currently fixed and not configurable.

### Bludit version
All.

**Comment by dignajar** [comment] 2019-01-16 17:40
Maybe is possible to create a plugin for this links; The plugins for the dashboard are possible, like the plugin `simple stats`.

**Comment by erdifr** [comment] 2019-04-05 00:31
After reading this it made me want to try and make a plugin for this. After some trial and error I finally have a rough working prototype.

Once installed and activated the plugin adds a second "Quick Links" section to the admin dashboard. I can already hear the questions. Why make a plugin that does the same thing? Well I did it this way because of @dignajar's comment. If "Quick Links" was turned into a working plugin it could be removed from Bludit [core] helping to keep Bludit lean while keeping the same ability as an option.

Currently the plugin provides 6 configurable quick link slots and has 10 internal links and 3 external link choices. [More information available here](https://github.com/erdifr/quick-links).

What doesn't work as intended yet? The settings config menu selection area. The options can be set, updated, saved, etc, but they don't display the active link names like I intended yet. Below is a screenshot to show what I mean.

![quick-links_screenshot](https://user-images.githubusercontent.com/21232590/55596414-5fd1e900-5716-11e9-9866-3d1b57df3b68.png)

Instead of showing ```qlContentNew``` it should show ```Content New``` or instead of ```qlCategories``` it should be ```Categories```, and so on for the other links.

Other than that issue everything is working as intended. I am sure there is repetitive code or things that could be done better. Hopefully there isn't anything to terrible in the code. I am open to suggestions and comments about how to make [this plugin better](https://github.com/erdifr/quick-links).

Hey @BlakesHeaven, is this remotely close to what you are after?

**Comment by BlakesHeaven** [comment] 2019-04-06 08:26
Hi @erdifr, well done, this looks like it is heading the right direction.
I'm probably at best a novice at php coding but I'll have a look at your code and see if I can suggest anything regarding the issues you mentioned. 
Thanks for doing this! 🙂

**Comment by erdifr** [comment] 2019-04-06 22:08
You're welcome @BlakesHeaven. I am pretty new to php myself so I appreciate any thoughts or suggestions you may have to make the plugin better. Hopefully with some teamwork this will turn into a great plugin.

**Comment by erdifr** [comment] 2019-04-07 01:08
Did some more tinkering with the plugin and I think that I have found a solution for the settings config menu selects. Instead of showing ```qlContentNew```, ```qlCategories``` and so on it now shows ```Select a link``` for each link option. Hopefully doing it this way isn't confusing.

Still haven't figured out a solution for updating/changing the outputted HTML when a menu item (or items) are disabled. Disabling links still works and it also leaves empty divs with styling when menu items are disabled. Not really ideal.

[Here's a link to the diff](https://github.com/erdifr/quick-links/commit/c125426a967907256717d8734c559da442a92a8d). As always I welcome any and all comments and/or thoughts.

**Comment by dignajar** [comment] 2022-02-22 16:04
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues

**Closed by dignajar** 2022-02-22 16:04 UTC
Labels: New request, Plugin
