### ISSUE TITLE
Hitcounter

### ISSUE THREAD

**Issue by bluditbeginner** [bludit/bludit#874] opened 2018-11-30 07:35 UTC
the Bludit-integrated Hitcounter (Bludit 3.4.0) has no effect in theme Theme Clean Blog.
No counts are visible on website.
Is the problem, that Clean Blog has no sidebar?
Is it possible to integrate the hitcounter in Clean Blog too?

**Comment by ccbc** [comment] 2018-12-01 19:54
I had the same issue with another theme. Dimo found the problem and fixed it.
The problem is probably that the following code is missing from index.php (in the theme folder).

`<?php Theme::plugins('siteBodyEnd'); ?>`

Just add at end of index.php before closing </body> tag.

**Comment by dimobelov** [comment] 2018-12-03 08:18
Hit counter have another hook. He is rendered on site Sidebar. So just add in your theme where you want to view hitcounter this code:  `<?php Theme::plugins('siteSidebar'); ?>` https://github.com/bludit/bludit/blob/14c893bb77681d3b8995cc0b2a876b4d4a6a4634/bl-plugins/hit-counter/plugin.php#L54

**Comment by bluditbeginner** [comment] 2018-12-03 21:19
Thanks for help dimobelov.
When i include the code, a complete sidebar (including hitcounter) is visible. But the website should not have a sidebar (theme Clean Blog). My wish is only to have the hitcounter at bottom of the page.
Is that easily possible?

**Comment by bluditbeginner** [comment] 2018-12-04 18:48
After watching the Source-Code I noticed, that the HitCounter "only" shows the visits for the current day.
It would be a nice feature to have a Counter for all visits too. But I think the SimpleStats plugin is not serving this data.
Perhaps it is a feature for future.

**Comment by BlakesHeaven** [comment] 2018-12-04 20:22
Hi, I wanted to keep this secret until it was fully ready, but I have been working for a while now to make it do exactly this and I am nearly there!  I have a working model of Simple Stats that captures not only Daily, but also Weekly, Monthly and a running total. The trouble is I'm not really a PHP programmer and what might take others here only hours, takes me weeks. Anyway, I just need to alter the HitCounter Plugin to use the right method to return the value of choice. I do have some thoughts for performance improvements, however, I am inclined to now do a pull request sooner for @dignajar to consider. I try and get it there soon.

**Comment by dignajar** [comment] 2018-12-05 14:33
Hi, sorry for my late answered.

You can call the plugin Hit-Counter like this.
```
if ( pluginActivated('pluginHitCounter') ) {
        $hitcounter = getPlugin('pluginHitCounter');
        echo $hitcounter->siteSidebar();
}
```

or you can call directly the plugin simple stats to avoid the HTML output from the hitcounter plugin.

```
if ( pluginActivated('pluginSimpleStats') ) {
        $simpleStats = getPlugin('pluginSimpleStats');
        $currentDate = Date::current('Y-m-d');
        $counter = $simpleStats->visits($currentDate);

        echo $counter;
}
```

I prefer the second option.

Regards

**Comment by dignajar** [comment] 2018-12-05 14:40
> After watching the Source-Code I noticed, that the HitCounter "only" shows the visits for the current day.
> It would be a nice feature to have a Counter for all visits too. But I think the SimpleStats plugin is not serving this data.
> Perhaps it is a feature for future.

I don't understand why you need to show to the users your hitcounter from previus days. The plugin Simple stats plugin shows in the dashboard a 7 days of hits.

**Comment by bluditbeginner** [comment] 2018-12-06 08:03
thanks dignajar for code-snippets to include the hitcounter in theme.

In my opinion the number of visits on the page are intersting not only for the current day. It is a fast way for users and for the owner of the website to get a view if the site is used (with no need of login to admin area - the owner and the admin are not the same person at all). And i think the information for dayly / weekly / monthly / all visits could be helpful.

An idea for the Simple Stat: 
Perpaps could the date and the number of visitors be logged in a extra file on server. So it is easy to load the file from server and display the data in excel or other programs. So the admin of the site gets a view to the visits to the site for all the time it is online. The values could be saved to the log-file before the files for count the dayly visits are deleted. Perhaps about this logfile the visibility of visits described above could be managed. It is only an idea of me.

**Comment by dimobelov** [comment] 2018-12-07 20:08
On a large site this will kill sever. Imagine that you have 3,000 real time visitors each second. And for each one Bludit opens, writes, closes a file. For the things you describe better use a specialized analytic code - Google , Yndex.

**Comment by bluditbeginner** [comment] 2018-12-09 17:07
The issue is handled by code-snippets form @dimobelov  and @dignajar . Thank for that.

@dimobelov : A comment to my idea of getting info of history of visit-counts:
Perhaps it is a misunderstanding or a bad description of me. So I try to describe more detailed.
If my idea is nonsens, so please ignore it ;-)
I looked in file plugin.php of plugin Simple Stats. There is a function deleteOldLogs(). I think this function is working only one time a day. My idea was, that when this function is called and before the dayly logfile is deleted (rmfile...) the number of visits/visitors with the according date could be written in an extra logfile. So the are 20-30 Bytes per day to log (date, visits and visitors).

Greetings.

**Comment by dignajar** [comment] 2018-12-27 08:57
Hi, I'm checking the issues and this topic is related to a new request. Can you create a new issue with the topic new plugin and describe what do you expect.
The hitcounter and the simple stats are really small plugins, and the idea is keep them like that to not complicate the users.
Regards

**Closed by dignajar** 2018-12-27 08:57 UTC
