### ISSUE TITLE
REMOTE CODE EXCEUTION BY FILE UPLOAD IN bludit version 3.12.0

### ISSUE THREAD

**Issue by effortlessdevsec** [bludit/bludit#1224] opened 2020-07-04 18:54 UTC
### Describe your problem
REMOTE CODE EXCEUTION BY FILE UPLOAD IN bludit version 3.12.0

### Steps to reproduce the problem
1. LOGIN TO ADMIN PANEL
2. GO TO NEW CONTENT AND UPLOAD IMAGE AND CAPTURE THE REQUEST WITH ANY PROXY TOOL.
3. AFTER THAT CHANGE IMAGE CONTENT TO `<?php phpinfo(); ?>` . image uploaded
4. NOW GO TO http://127.0.0.1/testing/bludit-3.12.0/bl-content/uploads/pages/XXXXXXX/file.jpg
5 . php code executed.

### Bludit version
3.12.0

![sdsds](https://user-images.githubusercontent.com/30777722/86519120-52de0100-be55-11ea-8eac-fd6391087ad0.png)
![dfdfdfsdf](https://user-images.githubusercontent.com/30777722/86519126-67ba9480-be55-11ea-9a73-214e8075d475.png)

**Comment by SamBrishes** [comment] 2020-07-04 19:15
Hellow,

this issue is a duplicate of #1218 and has already been fixed in the latest master branch (see Pull Request #1219). 

~ Sam.

**Closed** 2020-07-13 09:55 UTC
