### ISSUE TITLE
image upload mime_content_type check

### ISSUE THREAD

**Issue by LiohMoeller** [bludit/bludit#1238] opened 2020-07-16 17:56 UTC
In the recent 3.13.0 update a function has been added to upload-images.php and some variables to variables.php which should check the MimeType of an uploaded file using the mime_content_type check php functionality. The latter has been marked as deprecated and does not work on my Server with php 7.3. 

In order to be able image upload with this version again, either the MimeType check has to be removed or the function has to be re-implemented using Fileinfo which is the successor of mime_content_type check.

**Comment by dignajar** [comment] 2020-07-19 17:10
Hi,this issue was solved.

Looks like the function `mime_content_type` is not deprecated.
https://www.php.net/manual/en/function.mime-content-type.php

**Comment by zongdeiqianxing** [comment] 2020-07-23 07:32
> Hi,this issue was solved.
> 
> Looks like the function `mime_content_type` is not deprecated.
> https://www.php.net/manual/en/function.mime-content-type.php

when i upload a image in php5.6 or php7.0 , it will return 500 error .
the error is at upload-images.php:68 , may be it caused by the 'mime_content_type'

**Comment by dignajar** [comment] 2020-07-23 08:26
can you provide the logs ?

**Comment by zongdeiqianxing** [comment] 2020-07-23 11:36
I just insert the 'ajaxResponse("xxx");' at the 68 , and it return 500 code  .  
When inserted before line 68 it return 'ajaxResponse("xxx");'

**Comment by dignajar** [comment] 2020-07-23 13:13
do you have access to the server logs ? called php_error.log ? because I would like to know what happen in the server side

**Comment by zongdeiqianxing** [comment] 2020-07-24 01:07
[24-Jul-2020 09:00:52 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type() in C:\phpStudy\WWW\bl-kernel\helpers\filesystem.class.php:311
Stack trace:
#0 C:\phpStudy\WWW\bl-kernel\ajax\upload-images.php(69): Filesystem::mimeType('C:\\Windows\\php6...')
#1 C:\phpStudy\WWW\bl-kernel\boot\admin.php(50): include('C:\\phpStudy\\WWW...')
#2 C:\phpStudy\WWW\index.php(37): require('C:\\phpStudy\\WWW...')
#3 {main}
  thrown in C:\phpStudy\WWW\bl-kernel\helpers\filesystem.class.php on line 311
[24-Jul-2020 09:00:57 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type() in C:\phpStudy\WWW\bl-kernel\helpers\filesystem.class.php:311
Stack trace:
#0 C:\phpStudy\WWW\bl-kernel\ajax\upload-images.php(69): Filesystem::mimeType('C:\\Windows\\php7...')
#1 C:\phpStudy\WWW\bl-kernel\boot\admin.php(50): include('C:\\phpStudy\\WWW...')
#2 C:\phpStudy\WWW\index.php(37): require('C:\\phpStudy\\WWW...')
#3 {main}
  thrown in C:\phpStudy\WWW\bl-kernel\helpers\filesystem.class.php on line 311
[24-Jul-2020 09:01:06 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type() in C:\phpStudy\WWW\bl-kernel\helpers\filesystem.class.php:311
Stack trace:
#0 C:\phpStudy\WWW\bl-kernel\ajax\upload-images.php(69): Filesystem::mimeType('C:\\Windows\\php9...')
#1 C:\phpStudy\WWW\bl-kernel\boot\admin.php(50): include('C:\\phpStudy\\WWW...')
#2 C:\phpStudy\WWW\index.php(37): require('C:\\phpStudy\\WWW...')
#3 {main}
  thrown in C:\phpStudy\WWW\bl-kernel\helpers\filesystem.class.php on line 311



use php5.6 and php7.0 in phpstudy 2016 will report this error .
![image](https://user-images.githubusercontent.com/34082644/88352595-df148180-cd8c-11ea-8b17-c94aa71eb109.png)

**Comment by dignajar** [comment] 2020-07-24 07:13
Thank you, looks like this function is not installed by default in PHP. I will try to do some workaround.

**Comment by SamBrishes** [comment] 2020-07-27 16:32
The `mime_content_type` function is provided by the `fileinfo` PHP extension, **which is (or should be) enabled per default**. The function is also not deprecated, even if it was due to a mistake [back on the good old PHP 5.3x times](https://stackoverflow.com/questions/1263957/why-is-mime-content-type-deprecated-in-php).

There is no other easy possibility to read out the mime type, since the only alternative `file_info` function depends on the mentioned extension as well.

The only possible way I found is to read out the magic number and evaluate them directly, which - of course - is not possible on plain/text files but should work on images, videos, sounds and also on PDFs. But maybe there is also another workaround.

**Comment by dignajar** [comment] 2020-07-28 13:21
I uploaded a workaround, this happen to a few users.

https://github.com/bludit/bludit/commit/86e0f69030440c82ae82e3b2f3bc11c1f54022f1

**Comment by dignajar** [comment] 2022-02-22 16:11
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues

**Closed by dignajar** 2022-02-22 16:11 UTC
