### ISSUE TITLE
Using a complex password on fresh install breaks the admin login

### ISSUE THREAD

**Issue by duke1102** [bludit/bludit#711] opened 2018-07-01 15:47 UTC
Hey!

So I installed a fresh copy of Bludit 2.3.4 today on my server (Ubuntu 18.04, PHP 7.2) and during the install used the following password:
> Z[P<AzV.\fQTNlbTq#FA\v8Zz.ipH}Fe

I then tried to login to the admin dashboard and got the error that the password is wrong.

After that I did another fresh install and the same error greeted me. When I used a less complex password without symbols it worked just fine. When I added some users via the admin dashboard and used the earlier mentioned complex password, it also worked without any issues.  

Seems like there's something in the first install script that breaks the correct storage of passwords with symbols.

**Edit:**
Okay, after using a normal password on install and then changing the admin password via the admin dashboard to the complex one mentioned also seems to break the login possibility.

**Comment by dignajar** [comment] 2018-07-01 17:11
Hi,
yes the problem is when I check the password I sanitized the string, and when I store the password is not sanitized.

Remove this line https://github.com/bludit/bludit/blob/master/bl-kernel/login.class.php#L86

I'm thinking to sanitize when saving the password as well.

**Comment by dignajar** [comment] 2018-07-17 12:48
Fixed for v3.0, the password is not sanitized.

**Comment by JedBurke** [comment] 2018-07-17 16:46
While this doesn't directly relate to the bug, are there any reasons why [password_hash](https://secure.php.net/manual/en/function.password-hash.php) and [password_verify](https://secure.php.net/manual/en/function.password-verify.php) aren't being used?

**Comment by dignajar** [comment] 2018-07-17 16:58
@JedBurke is a bug. I was checking these functions and are included in PHP>5.5. I'm still giving support to PHP 5.3.

**Comment by Mu9tafa-Online** [comment] 2018-07-17 17:33
@dignajar - I think it's reasonable to drop "PHP 5.3" support, every major Hosting Company is moving towards php 7+

**Comment by JedBurke** [comment] 2018-07-17 17:43
@dignajar I see, thank you for clarifying.

**Comment by dignajar** [comment] 2018-07-17 19:25
@Mu9tafa-Online I would like, at least give support from the version 5.6, I saw some statics the last year (2017) and the 30% of the web-servers are using PHP v5.3.

**Comment by clickwork-git** [comment] 2018-07-17 19:59
I would drop support to versions older than 5.6. As @Mu9tafa-Online pointed out every major hoster is moving towards PHP 7.1 and 7.2. Hoster that offer still 5.3 and 5.4 are not serious in my opinion.

http://php.net/supported-versions.php

**Comment by Mu9tafa-Online** [comment] 2018-07-17 20:24
@dignajar - I Agree with **5.6+** (It's Fair Enough).

**Comment by dignajar** [comment] 2018-07-25 21:51
This bug is fixed for the version 3.0.0.

**Closed by dignajar** 2018-07-25 21:51 UTC
Labels: bug
