### ISSUE TITLE
[Bug] pages numbers in images windows

### ISSUE THREAD

**Issue by RenaudILTIS** [bludit/bludit#1051] opened 2019-06-15 16:01 UTC

**Comment by RenaudILTIS** [comment] 2019-06-15 16:07
To have this issue : I had 4 images in the article, and then I tried to upload 4 more images in one time (with the Ctrl multi-selection).
Now the upload window is not working properly : the upload is working, but the progress bar stay red at the end of the upload and the image list is not updated (but the file is uploaded).

**Comment by clickwork-git** [comment] 2019-06-17 16:00
Yes, it's a bug. As a sort of workaround till it will be fixed you can close the editor and reopen it.

**Comment by RenaudILTIS** [comment] 2019-06-17 16:04
Yes, it's what I made. I listed the names of the files and insert them in the html. Thank you.

**Comment by dignajar** [comment] 2019-06-17 19:56
I feel the issue is the paginator is not updated after upload the images ?

**Comment by RenaudILTIS** [comment] 2019-06-18 05:44
Something like that.

**Closed** 2020-01-02 09:08 UTC
