### ISSUE TITLE
Preview is null when selecting preview while editing a blog post if you don't have popups enabled.

### ISSUE THREAD

**Issue by sergiotarxz** [bludit/bludit#1239] opened 2020-07-17 19:24 UTC
### Describe your problem

Preview is null when selecting preview while editing a blog post if you don't have popups enabled.

### Steps to reproduce the problem

Enter the post editing interface and press preview in a new installation of Firefox in GNU/Linux without any configuration changes you will need to open the javascript console. 

### Bludit version

3-13-0

### PHP version

PHP 7.4.6

### PHP logs

Unneeded, it is a javascript problem.

### Proposed solution

Use a method to show previews transparent to the user which doesn't require to open another tab, popup, window or whatever. (Maybe `iframes`?)

**Comment by clickwork-git** [comment] 2020-07-27 11:29
This is in my opinion a problem of the browser settings not Bludit.

**Comment by SamBrishes** [comment] 2020-07-29 04:40
I cannot reproduce this issue, neither on Windows nor on Linux (tried on my elementaryOS notebook). 

Popups, which are triggered on a click or key event should also be allowed per default on FireFox ([Source](https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting)).

> Is the pop-up shown after a mouse click or a key press?
> Certain events, such as clicking or pressing a key, can spawn pop-ups regardless of if the pop-up blocker is on. This is > intentional, so that Firefox doesn't block pop-ups that websites need to work.

**Comment by dignajar** [comment] 2022-02-22 16:11
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues

**Closed by dignajar** 2022-02-22 16:11 UTC
